### ISSUE TITLE
[03/02] Weekly Report

### ISSUE THREAD

**Issue by MaybeS** [MaybeS/Lab#100]
## TODO

- [ ] Amano
    - [ ] Expand to Tracking
    - [ ] Visualize crop test
    - [ ] YOLO v3
    - [ ] Total nvr-warp dataset train/test
    - [ ] Up-down split dataset train/test
- [ ] SiamVOS
    - [ ] Train, eval reproduce
- [ ] Research
    - [ ] EfficientDet eval
        - [ ] COCO

## Objective

Objective
