### ISSUE TITLE
[03/11] Weekly Report

### ISSUE THREAD

**Issue by jiunbae** [MaybeS/Lab#13]
## TODO

- [x] Paper reading 
    - [x] #3 
    - [x] #4 
    - [x] #5 
    - [x] #6 
- [x] Presentation (03/15)
- [x] ~(03/19) 실습 ppt 만들기
- [ ] Capstone Project Refactoring

## Objective

Find research area and main target to contribute

**Comment by MaybeS** [comment]
## After meeting(03/13)

- Segmentation will better parts
- In the case of human tracking, pose estimate help increase accuracy

**Comment by MaybeS** [comment]
- [ ] 다음주 (화) 실습 ppt 만들기

**Comment by MaybeS** [comment]
- Unified approach
- UberNet
- MOTS Dataset request
