### ISSUE TITLE
[04/01] Weekly Report

### ISSUE THREAD

**Issue by MaybeS** [MaybeS/Lab#27]
## TODO

- [ ] Pose estimation model test
- [ ] MOT based on Mask R-CNN detection results
- [ ] Paper Research (tracking with pose estimation)

## Objective

Objective

**Comment by MaybeS** [comment]
[04/04] arrange result of Mask R-CNN and run MOTDT

**Comment by MaybeS** [comment]
[04/04] 교수님 수업 자료 취합 만들기
[04/04] 연구실 보고서, 계획서 작성

**Comment by MaybeS** [comment]
[04/05] Naver AI Colloquium
