### ISSUE TITLE
[04/22] Weekly Report

### ISSUE THREAD

**Issue by jiunbae** [MaybeS/Lab#39]
## TODO

- [ ] Amano Detection
- [ ] Image sequence to relation net
- [x] MOT Evaluate on site
    - [x] Split train/val 
- [x] DL Exam
- [ ] Paper research

## Objective

Objective
