### ISSUE TITLE
[07/01] Weekly Report

### ISSUE THREAD

**Issue by MaybeS** [MaybeS/Lab#60]
## TODO

- [ ] Samsung vision class
- [ ] SSD with warping layer
- [ ] Mask RCNN with warping layer
- [ ] Mask RCNN with rotation anchor

## Objective

Objective

**Comment by MaybeS** [comment]
- [ ] pytorch.ssd 성능 재현
- [ ] mrcnn 성능 재현

**Comment by MaybeS** [comment]
- [ ] 데이터셋 충분한지 검사
- [ ] 워핑이 잘 되고있나 검사
