### ISSUE TITLE
[07/08] Weekly Report

### ISSUE THREAD

**Issue by MaybeS** [MaybeS/Lab#61]
## TODO

- [ ] amano network
    - [ ] check warping layer working
    - [ ] check dynamic kernel conv2D working
- [ ] check mrcnn eval (mAP)

**Comment by MaybeS** [comment]
- [ ] implement Mask RCNN logging metric result to tensorboard

**Comment by MaybeS** [comment]
- [ ] fron face annotation
