### ISSUE TITLE
[07/22] Weekly Report

### ISSUE THREAD

**Issue by MaybeS** [MaybeS/Lab#63]
## TODO

- [ ] Mask-RCNN attach evaluation to callbacks
- [ ] Amano additional dataset confirm
    - [ ] Annotation for new datasets
- [ ] Compare result of SSD trained by amano dataset to VOC

## Objective

Objective

**Comment by MaybeS** [comment]
- [ ] 노상 LPR 이미지에 대해 각 스텝마다 디텍션 결과 확인
- [ ] Fisheye view corn warping
- [ ] frontal-view alignment

**Comment by MaybeS** [comment]
- [ ] Inference fisheye view images to normal view trained a model
- [ ] Inference normal view images to the developed model.

**Comment by MaybeS** [comment]
- [ ] Inference monocular depth estimation to fisheye
- [ ] Dense annotation
