### ISSUE TITLE
[08/05] Weekly Report

### ISSUE THREAD

**Issue by MaybeS** [MaybeS/Lab#65]
## TODO

- [ ] Fisheye view detection model Improvement

## Objective

Objective

**Comment by MaybeS** [comment]
# Lab 

from ep10


| Model | mAP | Precision | Recall | Counts(800) |
| --- | --- | --- | --- | --- |
|base|18.93|.456|.415|738|
|atrous|25.24|.559|.452|731|
|atrous-max|11.03|.262|.421|1618|
|atrous-max-nomask|23.69|.535|.443|789|

**Comment by MaybeS** [comment]
- [ ] Check LPR Module(C++)
    - [ ] Running on GPU(with device selection)
    - [ ] Remove unused classes

**Comment by MaybeS** [comment]
- [ ] Mask R-CNN with coco segment nan loss
- [ ] SSD Training stop at 4ep
