### ISSUE TITLE
[08/19] Weekly Report

### ISSUE THREAD

**Issue by MaybeS** [MaybeS/Lab#67]
## TODO

- [ ] LPR Detector
    - [ ] Image diff (new feature)
    - [ ] Performance improve
- [ ] Fisheye network
    - [ ] Attach image classifier
    - [ ] Corn warping result anaylsis 

## Objective

Objective
