### ISSUE TITLE
[09/09] Weekly Report

### ISSUE THREAD

**Issue by MaybeS** [MaybeS/Lab#70]
## TODO

- [ ] Amano
    - [ ] Amano Tech Report refactoring
    - [ ] Amano LPR Inference on YOLO and SSD(visualize video)
    - [ ] Amano Fisheye Detector care boundary and angle to center
- [ ] Test dataloader of pytorch(for best, in case of parallel processing, loader is bottleneck)

## Objective

Objective
