### ISSUE TITLE
[09/16] Weekly Report

### ISSUE THREAD

**Issue by MaybeS** [MaybeS/Lab#71]
## TODO

- [ ] 09/23Object detection and segmentation with Domain Adaptation Review
- [ ] SSD amano warping network
- [ ] PyTorch Data Loader

## Objective

Objective
