### ISSUE TITLE
[10/07] Weekly Report

### ISSUE THREAD

**Issue by MaybeS** [MaybeS/Lab#75]
## TODO

- [ ] Amano LPR-visualize GUI
    - [ ] DLL check
    - [ ] Win32 Modal implement
- [ ] EWE8043 paper slide
    - [ ] EWE8043 paper support research
- [ ] Amano FisheyeNet Implement
    - [ ] VGG features warping only (not extras)
    - [ ] `NaN` loss check
    - [ ] Evaluation result research

## Objective

Objective
