### ISSUE TITLE
[02/17] Weekly Report

### ISSUE THREAD

**Issue by MaybeS** [MaybeS/Lab#98]
## TODO

- [ ] Amano
    - [ ] Expand to Tracking
- [ ] SiamVOS
    - [ ] Train, eval reproduce
- [ ] Research
    - [ ] ~~pytorch-ssd original mb2 eval~~
    - [ ] EfficientDet eval
        - [ ] COCO

## Objective

Objective
